### ISSUE TITLE
adding a revocation id in the common keys?

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#1]
we do not specify a revocation system here, but support for a revocation id (that would allow revoking a token and all its derived tokens) could be useful

**Comment by clementd-fretlink** [comment]
ideally, revocation ids could also be inserted when attenuating a token.

Inserting a caveat carrying a revocation id is how I'd implement it with macaroons, but here maybe we could derive one from the token itself?

**Comment by Geal** [comment]
yes, it should be possible to derive a revocation id from a hash of the token or something

**Comment by Geal** [comment]
revocation ids can introduce issues with attenuation, if someone adds a block with a revocation id that is already used elsewhere. If we want to revoke that id, it might invalidate another token.

here's an idea we have been playing with to solve that: each block's revocation id adds a suffix to the previous block's.
We could have a token with the following ids: `1234`, `1234-5678`, `1234-5678-9ABC`, etc.
To check revocation status:
- run a query to gather all the revocation ids
- sort them by length
- check that each id is a suffix of the preceding one
- look up each of those ids in the revocation database

With the prefixes, we're sure that each token has a unique serie of ids (as long as each new prefix is unique, though)

When adding a new block:
- run a query to gather all the revocation ids
- sort them by length
- generate a new id
- take the longest revocation id from the list, concatenate with the new id

This scheme could be implemented externally, with just some datalog queries.

Generating revocation ids from token hashes would need tighter integration in Biscuit, but would have the same effect. 1st block's revocation id is the raw block data's hash, 2nd block's id is the hash of the first block's id and the 2nd block's raw data, etc.

**Comment by clementd-fretlink** [comment]
based on my experience with macaroons, having revocation ids computed from token hashes would be better (if tokens hashes have a source of randomness), as it would allow to revoke biscuits without having to add revocation ids in advance.

Without that, rolling out revocation ids means that one have to invalidate previously emitted tokens, which is rather heavyweight.

**Comment by clementd-fretlink** [comment]
Hi again, after having rolled out a revocation infrastructure for macaroons, I can double down on "each biscuit should be uniquely identifiable and revokable from its creation".

**Comment by Geal** [comment]
revocation ids are now available in bf3f7b26d7207a8aa64c9
Rust version: https://github.com/CleverCloud/biscuit-rust/commit/451690c5960c99e18930201dfcf1b5efdbe4a090

**Comment by meh** [comment]
Out of curiosity, why was SHA256 picked for this?

**Comment by Geal** [comment]
any hash function would have been a good fit here. I was thinking that using SHA512 again here would make larger revocation lists than SHA256 (32 VS 64 bytes) for no added benefit, that's all.

**Comment by meh** [comment]
I was more thinking BLAKE3 because I'm using that everywhere on my stuff, but I guess implementation is not that common in Java and other languages?

**Comment by Geal** [comment]
I like blake too, but it's not that common, yes. And Biscuit already requires a SHA2 implementation anyway

**Comment by clementd-fretlink** [comment]
(this stems from experience with macaroons where token generation is deterministic as well)
