### ISSUE TITLE
Consider renaming larger

### ISSUE THREAD

**Issue by Keruspe** [CleverCloud/biscuit#23]
Usually, we speak in terms of lower/greater and not lower/larger

**Comment by Geal** [comment]
Spec: https://github.com/CleverCloud/biscuit/commit/456549d82a59904783198711d4f405fa6c897ffc
Rust: https://github.com/CleverCloud/biscuit-rust/commit/01f1ba0f9a32304a68a3fe67d667d50d4eafff50
