### ISSUE TITLE
node js implementation

### ISSUE THREAD

**Issue by josselinchevalay** [CleverCloud/biscuit#25]
Hello guys, 

Have you thought about an implementation in node js ?

Regards

**Comment by Geal** [comment]
most implementations will wrap the Rust library. We're writing one specific for Java because external library integration is a bit more complex there, and it allows us to check that implementation details are correctly specified. But for platforms like Node it will be much easier to use Rust

**Comment by josselinchevalay** [comment]
with this approach : https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm ?

**Comment by Geal** [comment]
yes, wrapping it in wasm will be the easiest way (and we want it to be usable in frontend code as well)

**Comment by josselinchevalay** [comment]
nice thx a lot
