### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by titanous** [CleverCloud/biscuit#26]
Please add a license to this repo and biscuit-rust/java. Thanks!

**Comment by Geal** [comment]
Hello! all the work is now licensed under Apache 2:
https://github.com/CleverCloud/biscuit/commit/0bbd24003537d24de040282cea00a4cf651cf795
https://github.com/CleverCloud/biscuit-java/commit/086a0015c5c9cbe6258574f3ad8ce461e36257e8
https://github.com/CleverCloud/biscuit-rust/commit/916c0098c5b8c76f35cb47a9b48cb3b5dba66e48

**Comment by titanous** [comment]
Awesome!
