### ISSUE TITLE
removing the authority tag? Or merging block before validation?

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#34]
The first block of a token is called the "authority block", and is used to define some rights and rules that will be used when validating other blocks. here is the process:
- load facts and rules from the authority block
- load ambient facts and rules from the verifier
- test authority caveats and verifier caveats
- take a snapshot of the current facts and rules
- for each following block:
  - start from the snapshot
  - add the block's facts and rules
  - test the block caveats
  - test the verifier caveats

Facts from the authority block (either directly or generated from rules) start with the `#authority` symbol to differentiate them from facts generated in the other blocks. This was useful in earlier versions, where data generated in one block's validation could be carried over to the next block: we wanted to avoid accidentally increasing rights by adding more authority facts for the validation in the next blocks.

Since the validation of each block is independent from the other ones, a block adding a fact can only affect its own validation, so I do not think the authority tag is still needed. The only issue I would see is in verifier queries that would try to list the facts we can access, but since it would get the facts from each block then return their intersection, a block adding more facts would have no effect. For queries that return the union of results (like revocation ids), we would need to be more careful. Maybe we should mark separately "filter queries" and "aggregation queries"?

This can simplify Biscuit significantly:
- no separation between block and authority caveats in the verifier
- no separation between block and authority queries in the verifier (like getting revocation ids)
- no need for separate `add_authority_*` methods at token creation
- no more checks for the creation of authority facts in later blocks
- most examples will look simpler without the authority symbol everywhere

**Comment by tarcieri** [comment]
Sounds like you've come full circle back to the Macaroons caveats model.

**Comment by Geal** [comment]
maybe. I could also go the other way and allow data to cross between blocks, which would allow a block requiring data coming from a later one, etc.

**Comment by Geal** [comment]
that could even be a bit simpler for the validation: load everything from every block, run the validation in one pass

**Comment by Geal** [comment]
ok so I tried both approaches in pull requests on the Rust version.

My feelings on those:
- removing the authority tag: pretty printing of tokens is cleaner, and we could remove the distinction between authority and block facts and rules, which can be a bit confusing in the API. The change is mainly cosmetic though
- merging blocks: the verifier API and behaviour get a lot simpler. Queries return data from the entire world, instead of per block. The data could even be printed and inspected after validation (so I could separate the queries from the validation phase). Some caveats that needed to differentiate between the authority block and the others are now simpler to write. It is now possible to write caveats that require later blocks to provide some facts (hello structural caveats and third party caveats!). It will require more care when writing rules though, to avoid elevating rights accidentally

**Comment by Geal** [comment]
In the end, merging blocks makes a nice API where queries can be separated from the caveats verification, and the generated facts can be inspected after running the caveats. I can also restart verification with different ambient data, which will help for further use cases.

**Comment by Geal** [comment]
merging blocks was added to the specification in db71970
