### ISSUE TITLE
Datalog format specifications

### ISSUE THREAD

**Issue by daeMOn63** [CleverCloud/biscuit#42]
Hello ! 
While checking the language format in the specification (https://github.com/CleverCloud/biscuit/blob/master/SPECIFICATIONS.md#logic-language) and the recent commits (https://github.com/CleverCloud/biscuit/commit/0b015a6ce7775446f114891593c55863a6fa5ded#diff-03a3756d2f8eaaf446a958595f62f98f), I'm unsure what is the latest format to be used, seeing variables defined as 0?  or $0, * prefix on caveats, ! prefix on predicate, @ on conditions... 

So I'm wondering what is the most up to date version of the syntax I could follow ?

Thanks!

**Comment by Geal** [comment]
it's up to date now, the samples folder should have nough examples if needed: https://github.com/CleverCloud/biscuit/commit/243c16b8ac4c8502e2d3aaaaa6954b4d8ef7ddf0
