### ISSUE TITLE
allowing variables in constraints

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#47]
Right now the values used in contraints are statically defined in the rule or caveat, but it could be useful to make them more dynamic.
As an example, if we wanted to define that the owner of a folder has all rights on any file in that folder or its subfolders, we would be able to write the following rule (with variable names instead of numbers for readability):

```
right($path, $operation) <- user($user_id), owner($user_id, $folder), operation($operation),
  resource($path) @ path matches $folder*
```

With that rule, we can define a path prefix constraint using the folder defined in the `owner` fact.

With this we could also compare integer variables between facts, and I think there could be some applications with set constraints too.

This would be a breaking change in the binary format.

**Comment by Geal** [comment]
@daeMOn63 any opinion on this?

**Comment by daeMOn63** [comment]
Looks cool! It opens lots of new options for rule and caveat definitions. I already have few spot in the signature flow where it could be helpful.

I'm still wondering if this won't make rules too complex or abstract, making it hard to see what it would produce and when it would apply, which could end being a bit dangerous in authorization flow. 

Also a bit afraid of potential injection / type confusion that can happen, if the user get some control over `$path` and `$folder`... Would need to experiment with it a bit!

**Comment by Geal** [comment]
yup, I'm planning to make a branch to test it out. There might be issues around typing too, I'd have to be careful

**Comment by Geal** [comment]
I'm currently working on integrating expressions, and I think I got a good design. First, it stays compatible with constraints, as constraints are a subset of the expressions. It will be serialized and executed as a serie of opcodes on a stack machine. As an example:

```
-1 < $var1
```

Would be serialized as:

```
Int(1), Negate, Variable(10), LessThan
```

Execution would work as follows:

```
// opcode, stack
Int(1)       []                // a raw value is pushed onto the stack
Negate       [Int(1)]          // a unary operation pops from the stack, applies the operation then pushes the result
Variable(10) [Int(-1)]         // we replace Variable(10) with the value we got from other facts, and push it on the stack
LessThan     [Int(-1), Int(0)] // a binary operation pops two values, applies the operation then pushes the result
```

When successful, the stack would contain only one value, a boolean. I also have the design for a pretty printer, than can generate a human readable expression from the opcodes.

To support it, we'll need new types:
- boolean, so they can be returned as value (also they might be used as flags in facts)
- sets, as proposed in #51, so they can be in integer, string, symbol and byte array constraints

We'll need some precise restriction on typing, like making sure that the `<` operator requires the same type on both sides (integer or date). There would still be a case where depending on the set of facts considered, the operator get ints on both sides, or dates on both sides.
If an operator gets an unexpected type (example: prefix operation with an integer), we stop execution and do not return a value.

For sets, I think we'll use a "set of IDs" as proposed in #51, but with some restrictions:
- all elements must have the same type
- if it contains variables, we fill all of them in when pushing the set onto the stack
- sets of sets are forbidden

For now, I'll work on reproducing all of the constraints, then I'll see how it can be extended.

I'm excited about this feature, because it will open up nice patterns, while keeping the code simple (right now I'm at about 130 lines of code for expression, each new operation adding 3 lines).

**Comment by Geal** [comment]
So, after a few more tests, I'll forbid sets containing variables too. There are a lot of pitfalls.
Example: we look up a fact containing a set with variables, so we need to find values for its variables. If there are multiple variables, we'll need to try all of their permutations (we don't know the correct mapping, only that they match some values in the real fact's set).
I'd rather have static sets for now, containing only ints, symbols, strings or byte arrays. They're much easier to work with, and they can be checked once during deserialization.
We can always figure out a better way to accept variable sets later.

**Comment by Geal** [comment]
current tests in https://github.com/Geal/biscuit-datalog-test
It can easily replace constraints: https://github.com/Geal/biscuit-datalog-test/blob/main/src/lib.rs#L861-L889
