### ISSUE TITLE
Using the symbol table for variable names in rules

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#48]
Variables are defined with an index, and this does not make them very readable. It would help to have variable names instead.
We could reuse the symbol table to provide those: a rule can still be stored with variables containing numbers, but those numbers could be indexes in the symbol table. They would be converted between names and numbers when generating the blocks or printing the rules.

The following rule:
```
*caveat1($0, $1) <- right(#authority, $0, $1), resource(#ambient, $0), operation(#ambient, $1)
```

could be printed as:
```
*caveat1($file, $operation) <- right(#authority, $file, $operation), resource(#ambient, $file), operation(#ambient, $operation)
```

**Comment by daeMOn63** [comment]
This is interesting! 
For the record, I've done something for this exact issue, but only as a preprocessing step to the parsing. It still allow to mix named and numbered variables and doesn't print rules with named variables when inspecting the biscuit, so it only help with the readability of the initial definition. 

Mixing both variable types doesn't seems to have any interest, and easing the inspection and debugging is a great plus, so I would be happy to have this :+1:

**Comment by Geal** [comment]
I mentioned it in the specification here: https://github.com/CleverCloud/biscuit/commit/828f4c38791f02077963d97f964989b6230b3378
It updates the samples since they are generated differently now by the Rust implementation: https://github.com/CleverCloud/biscuit-rust/commit/870c2f5f1f234e8e3dcab0033f62e4c236eef1c0

**Comment by Geal** [comment]
I've played a bit with it after implementation, and honestly I should have done that much sooner, it's great when there are complex rules :smile:

**Comment by Geal** [comment]
this is now done in the [Go implementation](https://github.com/flynn/biscuit-go/pull/37) and the [Java implementation](https://github.com/CleverCloud/biscuit-java/commit/ebc661413550f0a0bc116c6f4ce9152321f06870) as well
