### ISSUE TITLE
New atom type: Set

### ISSUE THREAD

**Issue by daeMOn63** [CleverCloud/biscuit#51]
It could be interesting to have a `Set` atom type in the spec.

We recently merged the feature into biscuit-go (see: https://github.com/flynn/biscuit-go/commit/19073ab908515f0e05662bc4084477f55e4e82dd)

This allows to group several atoms under a single one, and have constraints allowing to check if all or none the set values are included in a given set:

```
# given the fact:
users(#ambient, ["alice", "bob", "eve"])

# doesn't match, since eve is not in the constrained list
*allow($username) <- users(#ambient, $usernames) @ $usernames in ["alice", "bob"]

# match, $usernames does not contains any of "admin" or "root"
*allow($username) <- users(#ambient, $usernames) @ $usernames not in ["admin", "root"]
```

The set does not restrict embedding different atom types (ie: `[#a, "alice", 42]`) but I don't see much usage of that yet. It doesn't seem to affect the constraint anyway.

wdyt ?

**Comment by Geal** [comment]
it could reduce the number of facts we have to write but I worry a bit about the expected usage. If there's a Set atom type, how would we make a rule that generate a fact containing one? At best it would copy another set, while we might want to get intersection, union or difference operations too?

**Comment by daeMOn63** [comment]
> how would we make a rule that generate a fact containing one?

I'm not sure to see what you mean here, for me it's the same as for other atom types:
```
# copy the set
*new($usernames) <- users(#ambient, $usernames)

# create a new one ?
*new(["a", "b"]) <- users(#ambient, $usernames)
```

On  `intersection` / `union` / `diff` support, I'm not sure how it could go, as it doesn't fit in constraints. It sounds more like a new `operation` kind allowing to compute a new value and reinject it in the program.

For constraints on Set, I don't need anything more than "contains only" and "doesn't contains any" at the moment.

**Comment by Geal** [comment]
So creation would only be for a static set? I feel it would be more useful with set operations. On that topic ( I'll make it a separate issue), I'd like to support it, maybe as a new Expression atom type. That would allow constructing or combining values more easily.

Like, set construction could be:
`set_result(insert($set, $val)) <- set_result($set), value($val)`

**Comment by daeMOn63** [comment]
Yes, right now my use case is limited to static sets. Perhaps operations could get useful in more complex scenarios / attenuation use cases, but right now, I'd favor keeping it simple, at least to have it run and see how it behave. Same for expressions, I'd hold on it for now.  I'll probably come back to it once I'll have gathered some feedback and limitations on running what we currently have!

**Comment by Geal** [comment]
I'm adding sets to the spec: https://github.com/CleverCloud/biscuit/commit/f5169d225fa1756128cb16126faa89b5b173699c
Rust: https://github.com/CleverCloud/biscuit-rust/commit/bb47508c9b136ac4f83638d5d6d63494dbbe55a7

one slight difference with your implementation, sets are added to the v1 format only
