### ISSUE TITLE
nitpicking: renaming atom

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#52]
currently, we've been using *atom* to talk about *terms* while *atom* is generally used to desinate the predicates in the head and body of a rule

**Comment by Geal** [comment]
Rust version: https://github.com/CleverCloud/biscuit-rust/commit/11a17e3dffa608aff07dd52b1de11ef1e5841dc3
Java version: https://github.com/CleverCloud/biscuit-java/commit/1bd70a5527529038c7b2ff7a25ead9f793310ed4

**Comment by daeMOn63** [comment]
Go version: https://github.com/flynn/biscuit-go/commit/b7867bced193e954a1a02a772b53235485319707
