### ISSUE TITLE
explicit run time limits for the datalog engine

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#53]
right now, we put some hardcoded limits on the number of iterations in a "world run", but it should be better to leave that decision to the user. We can get a token with some degenerate cases that would produce a lot of facts or apply on a large number of iterations, so there should be a hard limit there.

A few options:
- limit on the number of facts produced
- limit on the execution time
- if we want a safer way, optionally forbid facts and rules in blocks other than authority (so those blocks would only contain caveats)

**Comment by Geal** [comment]
implemented in the Rust version: https://github.com/CleverCloud/biscuit-rust/commit/afa0042a20f3c1dd7fad27df5b96d22fa4f7d764
@daeMOn63 @titanous do you have such options for the Go version?

**Comment by Geal** [comment]
Java version: https://github.com/CleverCloud/biscuit-java/commit/ff9c2f6b37e96dddd999db5e9794d53cf4846807

**Comment by daeMOn63** [comment]
Implemented in Go version: https://github.com/flynn/biscuit-go/commit/747b88eaa048d534527fb2844a00148d49795b98
