### ISSUE TITLE
Text syntax changes

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#54]
the `*` character is used to indicate the head of a rule or caveat but it has been very confusing for users, so I'd propose that we remove it.

Additionally, I'd like to remove the head from caveats, or make it empty by default. W'll have to choose a new syntax for caveats. Something like `? <- fact1("term")` ?

Last one: there's a constraint on rules to produce facts that contain at least on term, but I'm not sure that constraint really makes sense, so maybe we could remove it

**Comment by Geal** [comment]
About empty rule heads, it is now supported in Rust https://github.com/CleverCloud/biscuit-rust/commit/6c5d1ff96a7b7c5dc773da70c61820c6e2367a7b and the Java version was already allowing it

**Comment by Geal** [comment]
the `*` prefix in rule heads is now removed.
spec: https://github.com/CleverCloud/biscuit/commit/cc6d55e0bdd12d456a81dfdad69cff15098f8314
Rust: https://github.com/CleverCloud/biscuit-rust/commit/2e9e65b3c5d515e22d347050759dbb7eaa787c68
Java: https://github.com/CleverCloud/biscuit-java/commit/65591651ee3ff35e2f1735e864dc8ce6b408d20a

**Comment by daeMOn63** [comment]
Empty head + `*` prefix removal in Go: https://github.com/flynn/biscuit-go/commit/747b88eaa048d534527fb2844a00148d49795b98
