### ISSUE TITLE
renaming In to Contains, removing NotIn

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#63]
I am changing the syntax for some operations to look like method operations, to do things like `"string".starts_with("str")`. For set operations `In` and `NotIn`, it will invert the arguments order: before we had `element, set, In`, now we would have `set, element, In`.

It could also be the right time to remove `NotIn` since we could write `!set.contains(element)` instead

**Comment by daeMOn63** [comment]
Looks like the samples are a bit off on the contains change (https://github.com/CleverCloud/biscuit/commit/01ea43fa9bb09bfc93d6c26e66cd4ec16fd661cc) ?
 they still seems to define `<var>.contains(<set>)` instead of `<set>.contains(<var>)`

**Comment by Geal** [comment]
you're right, I had not updated those, it should be fixed now with dda2bc1
